locale: "en-US"
title: SA NAY NAY OO
title_separator: "-"
logo: /assets/images/me280@0.5x.jpg
description: Frontend Mobile Developer | React Native | Node JS | FinTech | Digital Wallet | E-commerce |
show_downloads: false
theme: jekyll-theme-minimal